Repository SUSE/Portus, pull requests merged in 2018-12, with the labels that each got.

#2064 entity (repositories): reduced amount of rendered data
  app/controllers/explore_controller.rb
  lib/api/entities.rb
  spec/api/grape_api/v1/repositories_spec.rb
Labels: needs backport

#2068 Update from rails 5.2.1 to 5.2.2
  Gemfile.lock
Labels: just packaging, needs backport

#2078 ui: improved tag's row content
  app/assets/javascripts/modules/repositories/components/tags/delete-tag-action.vue
  app/assets/javascripts/modules/repositories/components/tags/tags-table-row.vue
  app/assets/javascripts/modules/repositories/components/tags/tags-table.vue
  app/assets/javascripts/modules/repositories/components/tags/vulnerabilities-preview.vue
  app/assets/javascripts/modules/repositories/services/vulnerabilities-parser.js
  app/assets/javascripts/shared/components/checkbox.vue
  app/assets/stylesheets/includes/forms.scss
  app/assets/stylesheets/includes/labels.scss
  lib/api/entities.rb
  spec/javascripts/modules/repositories/tags-table-row.spec.js
  spec/javascripts/modules/repositories/tags-table.spec.js
  spec/javascripts/modules/repositories/vulnerabilities-parser.spec.js
  spec/javascripts/modules/repositories/vulnerabilities-preview.spec.js
  spec/javascripts/setup.js
  spec/system/repositories_spec.rb
  vendor/assets/stylesheets/lifeitup/table.scss
Labels: review later
